// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace RoomRental.Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260707223244_seedDatabaseWithMoreData")]
    partial class seedDatabaseWithMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AddressId");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("apartment_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("province");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("street");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("suburb");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("ApartmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_addresses_apartment_id");

                    b.ToTable("addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            ApartmentId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "123 Main Street",
                            Suburb = "Berea"
                        },
                        new
                        {
                            Id = new Guid("aa803b77-3292-4d1b-86b9-6d3fe2576eef"),
                            ApartmentId = new Guid("759ecab4-ce31-441c-9e7f-47a69040a312"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "12 Msizi Drive",
                            Suburb = "Umlazi"
                        },
                        new
                        {
                            Id = new Guid("208a5e1c-3ab5-4157-9fad-b32654b4c9dc"),
                            ApartmentId = new Guid("7cc4c5d3-a093-4a3f-bcd9-695947d3b211"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "45 Nyandeni Road",
                            Suburb = "Umlazi"
                        },
                        new
                        {
                            Id = new Guid("b483ab33-3dae-4029-b901-b5c334fccc0f"),
                            ApartmentId = new Guid("3b0086b1-2a2f-4dd7-991f-fcb54114bed0"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "7 Bhekani Street",
                            Suburb = "Umlazi"
                        },
                        new
                        {
                            Id = new Guid("81bcd457-5d93-488a-bcda-79aafaead87f"),
                            ApartmentId = new Guid("0fcc7e71-9f73-4d7d-ba29-51b627eaed68"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "23 Mthembu Road",
                            Suburb = "KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("d84a9e60-201f-4d77-9c0a-04227ee460fe"),
                            ApartmentId = new Guid("5d9def3d-df8b-488b-906b-b553138c4250"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "89 Nkosi Street",
                            Suburb = "KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("2820c620-a856-47d8-b666-1828d3922eac"),
                            ApartmentId = new Guid("85defa89-e3b4-4880-afdb-7ef0b2a186f0"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "3 Dube Place",
                            Suburb = "KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("00d3e707-e057-43b1-92a5-63624a53a3ba"),
                            ApartmentId = new Guid("7a9029b4-09e3-4784-a371-6ab719ca10e1"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "15 Ntuzuma Road",
                            Suburb = "Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("ebbf0fde-ebb5-434c-bc56-1acb49400dd0"),
                            ApartmentId = new Guid("455ca4a3-209f-48ec-ba60-b6dcc79371bb"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "62 Zulu Street",
                            Suburb = "Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("20b407d9-fe7c-40a9-a811-bb055e515924"),
                            ApartmentId = new Guid("f42801fb-faa9-4cbd-b5ca-bc5e70138801"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "9 Maphumulo Drive",
                            Suburb = "Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("89051b63-50b2-4d8f-ac6e-26d9eb81cc79"),
                            ApartmentId = new Guid("86efdab8-4d9c-434e-ba4a-b2dac453edae"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "34 Clermont Main Road",
                            Suburb = "Clermont"
                        },
                        new
                        {
                            Id = new Guid("f2f3411c-3e6e-4265-a575-7d7002da0762"),
                            ApartmentId = new Guid("c6241678-eca6-4594-854c-5e2acf8abf81"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "78 Cele Street",
                            Suburb = "Clermont"
                        },
                        new
                        {
                            Id = new Guid("af1c9601-815f-4d17-a25d-8184f821e003"),
                            ApartmentId = new Guid("07112d1e-3fb9-4106-bb8d-d9c2e511707f"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "5 Buthelezi Road",
                            Suburb = "Clermont"
                        },
                        new
                        {
                            Id = new Guid("8347c94b-5dd2-40b0-9aca-38d6f0f2fcfd"),
                            ApartmentId = new Guid("0ee86b56-c90a-4e07-b07b-0c354b70f7f1"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "19 Lamontville Highway",
                            Suburb = "Lamontville"
                        },
                        new
                        {
                            Id = new Guid("2a523149-a8e9-4bba-859a-2ab489cded75"),
                            ApartmentId = new Guid("d176bf4a-33c8-44cc-989d-d7fb93c396cc"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "41 Ngcobo Street",
                            Suburb = "Lamontville"
                        },
                        new
                        {
                            Id = new Guid("997e1fc0-ee17-407b-9d4c-843eddaecc07"),
                            ApartmentId = new Guid("0b10b8bf-5562-4849-9369-09eaf18f679b"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "27 Mhlongo Drive",
                            Suburb = "Chesterville"
                        },
                        new
                        {
                            Id = new Guid("8bf583e7-a76a-4b98-84a3-3b27f86cfb7a"),
                            ApartmentId = new Guid("1901a0e4-3060-425c-b4ae-868ad3d60d8c"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "55 Khoza Road",
                            Suburb = "Chesterville"
                        },
                        new
                        {
                            Id = new Guid("6f3dd6a9-143f-4e7e-868b-8e2cd1165bb7"),
                            ApartmentId = new Guid("444dfb56-81b1-4404-991c-cfd2cf795bba"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "11 Sithole Street",
                            Suburb = "Chesterville"
                        },
                        new
                        {
                            Id = new Guid("5b6573b5-d980-4793-8636-3dfb35029d11"),
                            ApartmentId = new Guid("e7d194bc-c669-4ded-9690-4e8fff8978dc"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "38 KwaDabeka Road",
                            Suburb = "KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("e2d95181-6034-469a-90c9-a21faf97188b"),
                            ApartmentId = new Guid("18b47fc3-cfb3-42e3-8a2b-da76528f128c"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "72 Ndlovu Street",
                            Suburb = "KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("4db85c11-b6c1-4ba3-9ac3-8e109cebf2df"),
                            ApartmentId = new Guid("924977f3-d616-443f-9340-0805cfec43f3"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "6 Mthethwa Drive",
                            Suburb = "KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("79936c8c-67c3-4fd5-93ec-30125aefabc7"),
                            ApartmentId = new Guid("a226187c-69ff-4537-93c7-6629fa51f55d"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "29 Chatsworth Centre Road",
                            Suburb = "Chatsworth"
                        },
                        new
                        {
                            Id = new Guid("ffbccbda-73e8-43f0-a80a-fd1f85972b29"),
                            ApartmentId = new Guid("204d39f6-6063-4cb9-9996-b787ed422f0c"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "84 Phoenix Main Road",
                            Suburb = "Phoenix"
                        },
                        new
                        {
                            Id = new Guid("62d6e954-2f4d-45c4-a1c8-9dcc2a132c53"),
                            ApartmentId = new Guid("926d45f1-6999-4634-bca9-01f3ef0c1fe0"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "17 Lotus Park Drive",
                            Suburb = "Chatsworth"
                        },
                        new
                        {
                            Id = new Guid("ba3fabbb-1830-4099-8c73-0648301f85c3"),
                            ApartmentId = new Guid("19c1f5ef-ef57-4169-8952-13fee6bf49a3"),
                            City = "Durban",
                            Province = "KwaZulu-Natal",
                            Street = "53 Phoenix Industrial Road",
                            Suburb = "Phoenix"
                        },
                        new
                        {
                            Id = new Guid("e8919bfe-f303-46b4-b84b-f84a16fabad1"),
                            ApartmentId = new Guid("dcc0854b-0c75-45da-8457-1871909a78eb"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "14 Edendale Road",
                            Suburb = "Edendale"
                        },
                        new
                        {
                            Id = new Guid("c9da969c-8d79-4386-83e0-573febb02b64"),
                            ApartmentId = new Guid("4b76ace7-8609-42b1-8cb7-2226dc499bb4"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "66 Mkhize Street",
                            Suburb = "Edendale"
                        },
                        new
                        {
                            Id = new Guid("a5c15dbe-c304-4026-9622-b9db1fd5232e"),
                            ApartmentId = new Guid("29015c46-992a-4d8f-a584-70a6c8be00cc"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "32 Sobantu Village Road",
                            Suburb = "Sobantu"
                        },
                        new
                        {
                            Id = new Guid("dbea8f89-cdb5-4cb3-bcc4-1039022e91d8"),
                            ApartmentId = new Guid("938a93ce-4020-419b-85d7-1f7d4cd0554b"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "8 Ngubane Drive",
                            Suburb = "Sobantu"
                        },
                        new
                        {
                            Id = new Guid("4974bb04-ebb3-456d-a3f2-cef34c494497"),
                            ApartmentId = new Guid("f0aa0d6a-5449-416e-92a7-3b4711fc57c2"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "43 Imbali Main Road",
                            Suburb = "Imbali"
                        },
                        new
                        {
                            Id = new Guid("f6b057a7-cf3d-45f0-81f9-fc528cf9d9c3"),
                            ApartmentId = new Guid("f4556404-fc0e-4adc-9e4e-4aacdadf2f0a"),
                            City = "Pietermaritzburg",
                            Province = "KwaZulu-Natal",
                            Street = "21 Ashdown Road",
                            Suburb = "Ashdown"
                        });
                });

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ApartmentId");

                    b.Property<int>("AvailableRooms")
                        .HasColumnType("integer")
                        .HasColumnName("available_rooms");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_apartments");

                    b.ToTable("apartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            AvailableRooms = 2,
                            Description = "A nice place",
                            Price = 1100m,
                            Title = "Cozy Studio"
                        },
                        new
                        {
                            Id = new Guid("759ecab4-ce31-441c-9e7f-47a69040a312"),
                            AvailableRooms = 3,
                            Description = "A well maintained family home in the heart of Umlazi. Close to schools, shops and public transport.",
                            Price = 2600m,
                            Title = "Spacious Family Home in Umlazi"
                        },
                        new
                        {
                            Id = new Guid("7cc4c5d3-a093-4a3f-bcd9-695947d3b211"),
                            AvailableRooms = 1,
                            Description = "Compact and affordable bachelor flat ideal for a working professional. Secure complex with parking.",
                            Price = 2800m,
                            Title = "Affordable Bachelor Flat in Umlazi"
                        },
                        new
                        {
                            Id = new Guid("3b0086b1-2a2f-4dd7-991f-fcb54114bed0"),
                            AvailableRooms = 2,
                            Description = "Newly renovated 2 bedroom unit with modern finishes. Walking distance to Umlazi Mega City.",
                            Price = 900m,
                            Title = "Modern 2 Bedroom in Umlazi"
                        },
                        new
                        {
                            Id = new Guid("0fcc7e71-9f73-4d7d-ba29-51b627eaed68"),
                            AvailableRooms = 3,
                            Description = "Spacious 3 bedroom house in a quiet street. Features a garden and secure parking.",
                            Price = 420m,
                            Title = "3 Bedroom House in KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("5d9def3d-df8b-488b-906b-b553138c4250"),
                            AvailableRooms = 1,
                            Description = "Affordable single room in a shared house. Ideal for students or young professionals.",
                            Price = 550m,
                            Title = "Budget Room in KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("85defa89-e3b4-4880-afdb-7ef0b2a186f0"),
                            AvailableRooms = 2,
                            Description = "Well kept 2 bedroom unit close to KwaMashu station. Easy access to the CBD.",
                            Price = 500m,
                            Title = "Cozy 2 Bedroom in KwaMashu"
                        },
                        new
                        {
                            Id = new Guid("7a9029b4-09e3-4784-a371-6ab719ca10e1"),
                            AvailableRooms = 3,
                            Description = "Large family unit in Ntuzuma with a yard and secure gate. Close to local amenities.",
                            Price = 3000m,
                            Title = "Family Unit in Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("455ca4a3-209f-48ec-ba60-b6dcc79371bb"),
                            AvailableRooms = 1,
                            Description = "Simple and clean single room for rent. Shared bathroom and kitchen facilities.",
                            Price = 1500m,
                            Title = "Single Room in Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("f42801fb-faa9-4cbd-b5ca-bc5e70138801"),
                            AvailableRooms = 2,
                            Description = "Comfortable 2 bedroom flat with tiled floors and burglar bars. Secure neighbourhood.",
                            Price = 850m,
                            Title = "2 Bedroom Flat in Ntuzuma"
                        },
                        new
                        {
                            Id = new Guid("86efdab8-4d9c-434e-ba4a-b2dac453edae"),
                            AvailableRooms = 4,
                            Description = "Large 4 bedroom home perfect for a big family. Has a garage and spacious backyard.",
                            Price = 1200m,
                            Title = "Spacious Home in Clermont"
                        },
                        new
                        {
                            Id = new Guid("c6241678-eca6-4594-854c-5e2acf8abf81"),
                            AvailableRooms = 2,
                            Description = "Clean and affordable 2 bedroom flat in Clermont. Close to taxi ranks and shopping.",
                            Price = 2900m,
                            Title = "Affordable Flat in Clermont"
                        },
                        new
                        {
                            Id = new Guid("07112d1e-3fb9-4106-bb8d-d9c2e511707f"),
                            AvailableRooms = 1,
                            Description = "Neat bachelor flat with own entrance. Ideal for a single working person.",
                            Price = 2200m,
                            Title = "Bachelor Pad in Clermont"
                        },
                        new
                        {
                            Id = new Guid("0ee86b56-c90a-4e07-b07b-0c354b70f7f1"),
                            AvailableRooms = 3,
                            Description = "Well located 3 bedroom house near Lamontville stadium. Good transport links to the city.",
                            Price = 2300m,
                            Title = "3 Bedroom House in Lamontville"
                        },
                        new
                        {
                            Id = new Guid("d176bf4a-33c8-44cc-989d-d7fb93c396cc"),
                            AvailableRooms = 1,
                            Description = "Affordable room in a family home. Shared kitchen and bathroom. Water and lights included.",
                            Price = 1600m,
                            Title = "Compact Room in Lamontville"
                        },
                        new
                        {
                            Id = new Guid("0b10b8bf-5562-4849-9369-09eaf18f679b"),
                            AvailableRooms = 2,
                            Description = "Neat 2 bedroom unit in Chesterville. Tiled throughout with a small stoep.",
                            Price = 3000m,
                            Title = "2 Bedroom Unit in Chesterville"
                        },
                        new
                        {
                            Id = new Guid("1901a0e4-3060-425c-b4ae-868ad3d60d8c"),
                            AvailableRooms = 3,
                            Description = "Comfortable family home with 3 bedrooms and a yard. Quiet street with good neighbours.",
                            Price = 650m,
                            Title = "Family Home in Chesterville"
                        },
                        new
                        {
                            Id = new Guid("444dfb56-81b1-4404-991c-cfd2cf795bba"),
                            AvailableRooms = 1,
                            Description = "Clean single room with own entrance. Close to public transport and local shops.",
                            Price = 1700m,
                            Title = "Single Room in Chesterville"
                        },
                        new
                        {
                            Id = new Guid("e7d194bc-c669-4ded-9690-4e8fff8978dc"),
                            AvailableRooms = 2,
                            Description = "Affordable 2 bedroom home in KwaDabeka. Secure yard with parking.",
                            Price = 2000m,
                            Title = "2 Bedroom Home in KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("18b47fc3-cfb3-42e3-8a2b-da76528f128c"),
                            AvailableRooms = 1,
                            Description = "Basic but clean room in a shared property. Water and electricity included in rent.",
                            Price = 1400m,
                            Title = "Budget Room in KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("924977f3-d616-443f-9340-0805cfec43f3"),
                            AvailableRooms = 3,
                            Description = "Large 3 bedroom home with a big yard. Ideal for a family looking for space.",
                            Price = 2200m,
                            Title = "Spacious 3 Bedroom in KwaDabeka"
                        },
                        new
                        {
                            Id = new Guid("a226187c-69ff-4537-93c7-6629fa51f55d"),
                            AvailableRooms = 2,
                            Description = "Modern 2 bedroom flat near Chatsworth Centre. Tiled floors, open plan kitchen.",
                            Price = 700m,
                            Title = "Modern Flat in Chatsworth"
                        },
                        new
                        {
                            Id = new Guid("204d39f6-6063-4cb9-9996-b787ed422f0c"),
                            AvailableRooms = 3,
                            Description = "Well maintained 3 bedroom home in Phoenix. Close to schools, temples and shops.",
                            Price = 700m,
                            Title = "Family Home in Phoenix"
                        },
                        new
                        {
                            Id = new Guid("926d45f1-6999-4634-bca9-01f3ef0c1fe0"),
                            AvailableRooms = 1,
                            Description = "Neat bachelor flat in a secure complex in Chatsworth. Good for a single professional.",
                            Price = 900m,
                            Title = "Bachelor Flat in Chatsworth"
                        },
                        new
                        {
                            Id = new Guid("19c1f5ef-ef57-4169-8952-13fee6bf49a3"),
                            AvailableRooms = 2,
                            Description = "Comfortable 2 bedroom unit in Phoenix close to the industrial area. Easy highway access.",
                            Price = 800m,
                            Title = "2 Bedroom Unit in Phoenix"
                        },
                        new
                        {
                            Id = new Guid("dcc0854b-0c75-45da-8457-1871909a78eb"),
                            AvailableRooms = 3,
                            Description = "Spacious 3 bedroom home in Edendale, Pietermaritzburg. Close to Edendale Hospital and schools.",
                            Price = 2500m,
                            Title = "Affordable Home in Edendale"
                        },
                        new
                        {
                            Id = new Guid("4b76ace7-8609-42b1-8cb7-2226dc499bb4"),
                            AvailableRooms = 1,
                            Description = "Clean single room in a family home in Edendale. Shared facilities. No pets allowed.",
                            Price = 1300m,
                            Title = "Single Room in Edendale"
                        },
                        new
                        {
                            Id = new Guid("29015c46-992a-4d8f-a584-70a6c8be00cc"),
                            AvailableRooms = 2,
                            Description = "Cozy 2 bedroom house in Sobantu village. Quiet area close to Pietermaritzburg CBD.",
                            Price = 2000m,
                            Title = "2 Bedroom House in Sobantu"
                        },
                        new
                        {
                            Id = new Guid("938a93ce-4020-419b-85d7-1f7d4cd0554b"),
                            AvailableRooms = 3,
                            Description = "Well kept 3 bedroom family unit in Sobantu. Yard with washing line and parking.",
                            Price = 1700m,
                            Title = "Family Unit in Sobantu"
                        },
                        new
                        {
                            Id = new Guid("f0aa0d6a-5449-416e-92a7-3b4711fc57c2"),
                            AvailableRooms = 3,
                            Description = "Spacious family home in Imbali, Pietermaritzburg. Close to schools and local amenities.",
                            Price = 1600m,
                            Title = "3 Bedroom Home in Imbali"
                        },
                        new
                        {
                            Id = new Guid("f4556404-fc0e-4adc-9e4e-4aacdadf2f0a"),
                            AvailableRooms = 2,
                            Description = "Neat 2 bedroom flat in Ashdown. Modern kitchen and bathroom. Secure complex.",
                            Price = 2300m,
                            Title = "Modern Flat in Ashdown"
                        });
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("apartment_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("ImageId")
                        .HasName("pk_images");

                    b.HasIndex("ApartmentId")
                        .HasDatabaseName("ix_images_apartment_id");

                    b.ToTable("images", (string)null);

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("1a2b3c4d-1234-5678-abcd-1a2b3c4d5e6f"),
                            ApartmentId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            Url = "https://picsum.photos/seed/picsum/200/300"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3d490a70-94ce-4d15-9494-5248280c2ce3",
                            ConcurrencyStamp = "3d490a70-94ce-4d15-9494-5248280c2ce3",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            ConcurrencyStamp = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            Name = "Renter",
                            NormalizedName = "RENTER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.HasOne("Entities.Models.Apartment", "Apartment")
                        .WithOne("Address")
                        .HasForeignKey("Entities.Models.Address", "ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_apartments_apartment_id");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.HasOne("Entities.Models.Apartment", "Apartment")
                        .WithMany("Images")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_images_apartments_apartment_id");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
